apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "true"
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kiali.org/helm-charts
      chart: kiali-operator
      version: 1.31.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: istio-system
      interval: 5m
  values:
    cr:
      create: true
      namespace: istio-system
