apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: istio-system
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.7.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: istio-system
      interval: 1m
  values:
    datasources:
      apiVersion: 1
      datasources:
        - access: proxy
          editable: true
          isDefault: true
          jsonData:
            timeInterval: 5s
          name: Prometheus
          orgId: 1
          type: prometheus
          url: http://prometheus:9090
    dashboardproviders:
      apiVersion: 1
      providers:
        - disableDeletion: false
          folder: istio
          name: istio
          options:
            path: /var/lib/grafana/dashboards/istio
          orgId: 1
          type: file
        - disableDeletion: false
          folder: istio
          name: istio-services
          options:
            path: /var/lib/grafana/dashboards/istio-services
          orgId: 1
          type: file
    extraConfigmapMounts:
      - name: config
        configMap: grafana
      - name: dashboards-istio
        configMap: istio-grafana-dashboards
      - name: dashboards-istio-services
        configMap: istio-services-grafana-dashboards
