apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-exporter
  namespace: flux-system
  annotations:
    fluxcd.io/automated: "true"
    meta.helm.sh/release-name: "helm-exporter"
    meta.helm.sh/release-namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://shanestarcher.com/helm-charts/
      chart: helm-exporter
      version: 0.7.3+0c5ff6f
      sourceRef:
        kind: HelmRepository
        name: shanestarcher
        namespace: flux-system
      interval: 5m
  values:
    serviceMonitor:
      create: true
      interval: 1m
      namespace: istio-system
