apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.7.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: istio-system
      interval: 5m
  values:
    datasources:
      apiVersion: 1
      datasources:
        - access: proxy
          editable: true
          isDefault: true
          jsonData:
            timeInterval: 5s
          name: Prometheus
          orgId: 1
          type: prometheus
          url: http://prometheus:9090
    dashboardproviders:
      apiVersion: 1
      providers:
        - disableDeletion: false
          folder: istio
          name: istio
          options:
            path: /var/lib/grafana/dashboards/istio
          orgId: 1
          type: file
        - disableDeletion: false
          folder: istio
          name: istio-services
          options:
            path: /var/lib/grafana/dashboards/istio-services
          orgId: 1
          type: file
    extraVolumeMounts:
      - name: config
        mountPath: /etc/grafana/grafana.ini
        subPath: grafana.ini
      - name: storage
        mountPath: /var/lib/grafana
      - me: dashboards-istio
        mountPath: /var/lib/grafana/dashboards/istio
      - me: dashboards-istio-services
        mountPath: /var/lib/grafana/dashboards/istio-services
      - me: config
        mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
        subPath: datasources.yaml
      - name: config
        mountPath: /etc/grafana/provisioning/dashboards/dashboardproviders.yaml
        subPath: dashboardproviders.yaml
    extraContainerVolumes:
      - name: config
        configMap:
          name: grafana
      - name: dashboards-istio
        configMap:
          name: istio-grafana-dashboards
      - name: dashboards-istio-services
        configMap:
          name: istio-services-grafana-dashboards
      - name: storage
        emptyDir: { } # yamllint disable-line rule:braces
