apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
    namespace: istio-system
    name: istio-default
spec:
    profile: default
    meshConfig:
        accessLogFile: /dev/stdout
        enableTracing: true
    components:
        pilot:
            k8s:
                resources:
                    requests:
                        cpu: 10m
                        memory: 100Mi
