apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://flagger.app
      chart: flagger
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: istio-system
      interval: 5m
  values:
    crd:
      create: false
    meshProvider: istio
    metricsServer: http://prometheus.istio-system:9090
