apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: cert-manager
spec:
    helmVersion: v3
    releaseName: cert-manager
    chart:
        repository: https://charts.jetstack.io
        name: cert-manager
        version: v1.2.0
    values:
        controller:
            replicaCount: 2
        installCRDs: true
